name: CI

on: [push]

env:
  CI: true

jobs:
  build:
    name: Build libllhttp.a
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Xtensa toolchain
        run: |
          mkdir toolchain
          pushd toolchain
          curl -sOL https://github.com/earlephilhower/esp-quick-toolchain/releases/download/3.2.0-gcc10.3/x86_64-linux-gnu.xtensa-lx106-elf-c791b74.230224.tar.gz
          tar xf x86_64-linux-gnu.xtensa-lx106-elf-c791b74.230224.tar.gz
          echo "$PWD/xtensa-lx106-elf/bin" >> $GITHUB_PATH
          popd

      - name: Fetch code
        uses: actions/checkout@v3
        with:
          path: build
          fetch-depth: 1

      - name: Install dependencies
        run: |
          pushd build
          npm install --ignore-scripts
          popd

      - name: Build libllhttp.a
        run: |
          pushd build
          make CC=xtensa-lx106-elf-gcc build/libllhttp.a
          popd

      - name: Upload libllhttp.a
        uses: actions/upload-artifact@v3
        with:
          path: build/build/libllhttp.a
